myblog/userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('register/', views.user_register, name="register"),
    path('delete/<int:id>/', views.user_delete, name='delete'),
]

myblog/userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
# 引入内置信号
from django.db.models.signals import post_save
# 引入信号接收器
from django.dispatch import receiver

# Create your models here.

# 用户信息拓展
class Profile(models.Model):
    # 与User模型构成一对一的关系
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    # 电话字段
    phone = models.CharField(max_length=20, blank=True)
    # 头像
    avator = models.ImageField(upload_to="avator/%Y%m%d", blank=True)
    # 个人简历
    bio = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return 'user{}'.format(self.user.username)

# 信号接收函数，每当新建User实例的时候，自动调用
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

# 信号接收函数，每当更新User时候自动调用
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()
    

myblog/userprofile/forms.py
# 引入表单类
from django import forms
# 引入User模型
from django.contrib.auth.models import User

# 登录表单，继承了forms.Form类
class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()


# 注册用户表单
class UserRegisterForm(forms.ModelForm):
    # 复写User的密码
    password = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        # 嵌套类，主要用于指定数据的一些属性
        model = User
        fields = ('username', 'email')

    # 对两次输入的密码进行检测
    def clean_password2(self):
        data = self.cleaned_data    # 对数据进行清洗，保留有用的数据
        if data.get('password') == data.get('password2'):
            return data.get('password')
        else:
            raise forms.ValidationError("输入的密码不一致，请重试")
    

myblog/userprofile/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from .forms import UserLoginForm
from .forms import UserRegisterForm
from django.contrib.auth.models import User
# 引入验证登录的装饰器
from django.contrib.auth.decorators import login_required

# Create your views here.
def user_login(request):
    if request.method == 'POST':
        user_login_form = UserLoginForm(data=request.POST)
        if user_login_form.is_valid():
            # .cleaned_data 清洗出合法的数据
            data = user_login_form.cleaned_data
            # 检测账号密码是否正确匹配数据库中的某个用户
            # 如果均匹配则返回这个user对象
            user = authenticate(username=data['username'], password=data['password'])
            if user:
                # 将用户的数据保存在session中，实现了登录的动作
                login(request, user)
                return redirect("blog:home")
            else: 
                return HttpResponse("账号或密码输入错误，请重新输入")
        else:
            return HttpResponse("账号或密码不合法")
    elif request.method == 'GET':
        user_login_form = UserLoginForm()
        context = {'form': user_login_form}
        return render(request, 'login.html', context)

    else:
        return HttpResponse("请使用GET或者POST请求数据")


# 退出登录
def user_logout(request):
    logout(request)
    return redirect("blog:home")

# 用户注册
def user_register(request):
    if request.method == 'POST':
        user_register_form = UserRegisterForm(data=request.POST)
        if user_register_form.is_valid():
            new_user = user_register_form.save(commit=False)
            # 设置密码
            new_user.set_password(user_register_form.cleaned_data['password'])
            new_user.save()
            # 保存好数据以后，立即登录并韩慧博客的列表页面、
            login(request, new_user)
            return redirect("blog:home")
        else:
            return HttpResponse("注册表单有误，请重新输入~")
    elif request.method == 'GET':
        user_register_form = UserRegisterForm()
        context = {'form': user_register_form }
        return render(request, 'register.html', context)
    else: 
        return HttpResponse("请使用GET或者POST请求数据")


@login_required(login_url='login')
def user_delete(request, id):
    user = User.objects.get(id=id)
    # 验证登录的用户和待删除的用户是否相同
    if request.user == user:
        # 退出登录，删除数据并返回到博客列表
        logout(request)
        user.delete()
        return redirect("blog:home")
    else: 
        return HttpResponse("你没有删除操作的权限")

myblog/userprofile/templates/login.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 登录 {% endblock title %}
{% block body %}
<div class="col-md-8">
            <br>
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                            <form method="post" action=".">
                                    {% csrf_token %}
                                    <!-- 账号 -->
                                    <div class="form-group">
                                        <label for="username">账号</label>
                                        <input type="text" class="form-control" id="username" name="username">
                                    </div>
                                    <!-- 密码 -->
                                    <div class="form-group">
                                        <label for="password">密码</label>
                                        <input type="password" class="form-control" id="password" name="password">
                                    </div>
                                    <!-- 提交按钮 -->
                                    <button type="submit" class="btn btn-primary">提交</button>
                                    <a href="{% url 'userprofile:register'%}">注册账号</a>
                                </form>
                    </div>
                </div>
            </div>
            
    
</div>
{% endblock body %}
{% block right-menu %}   {% endblock right-menu %}

myblog/userprofile/templates/register.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 登录 {% endblock title %}
{% block body %}
<div class="col-md-8">
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-4">
                <br>
                <form method="post" action=".">
                    {% csrf_token %}
                    <!-- 账号 -->
                    <div class="for">
                        <label for="username">昵称</label>
                        <input type="text" class="form-control" id="username" name="username" required>
                    </div>
                    <!-- 邮箱 -->
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="text" class="form-control" id="email" name="email">
                    </div>
                    <!-- 密码 -->
                    <div class="form-group">
                        <label for="password">设置密码</label>
                        <input type="password" class="form-control" id="password" name="password" required>
                    </div>
                    <!-- 确认密码 -->
                    <div class="form-group">
                        <label for="password2">确认密码</label>
                        <input type="password" class="form-control" id="password2" name="password2" required>
                    </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary">提交</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock body %}