article/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'article'

urlpatterns =[
    path('article/<int:aid>', views.article_show, name="detail"),
    path('category/<urlname>', views.category_list, name="category"),
    path('tags/<tag>', views.tag_list, name="tags"),
    path('search/', views.Search, name="search"),
    path('update/', views.update_comment, name="update_comment"),
    path('api/category/<urlname>', views.json_list, name="json_list"),
    path('comments/<aid>', views.get_comments, name="get_comment"),
    path('', views.index, name="home"),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from userprofile import urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('comment/', include('comment.urls', namespace='comment')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('mdeditor/', include('mdeditor.urls')),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seco/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('mdeditor/', include('mdeditor.urls')),
    path("", include('article.urls')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns =[
    path('login/', views.loginView, name="login" ),
    path('logout/', views.logoutView, name="logout" ),
    path('register/', views.registerView, name="register" ),
]

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse
from mdeditor.fields import MDTextField
# Create your models here.
# 创建models规定article的属性
from ckeditor.fields import RichTextField

# 分类
class Category(models.Model):
    
    name = models.CharField("分类名", max_length=50)
    father = models.ForeignKey("self", verbose_name="父级", on_delete=models.DO_NOTHING, null=True, blank=True)
    rank = models.IntegerField("分类等级", default=1)
    show = models.BooleanField("列表显示", default=True)
    urlname = models.CharField("url名称", max_length=50, default="all")

    class Meta:
        verbose_name = "分类"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 标签
class Tags(models.Model):
    
    name = models.CharField("标签名称", max_length=100)

    class Meta:
        verbose_name = "标签"
        verbose_name_plural = "标签 "

    def __str__(self):
        return self.name


# 文章
class Article(models.Model):
    
    title = models.CharField("标题", max_length=50)

    # context = models.TextField("文章内容")
    # 富文本编辑器
    context = MDTextField("文章内容")
    author = models.ForeignKey(User, verbose_name="作者", on_delete=models.CASCADE)
    category = models.ForeignKey(Category, verbose_name="分类", on_delete=models.DO_NOTHING)
    tags = models.ManyToManyField(Tags, verbose_name="标签")
    created_time = models.DateTimeField("创建时间", auto_now=False, auto_now_add=True)
    modefid_time = models.DateTimeField("修改时间", auto_now=True, auto_now_add=False)
    views = models.IntegerField("观看人数", default=0)
    img = models.ImageField("图片", upload_to="article/%Y/%m/%d/", height_field=None, width_field=None, max_length=None, null=True, blank=True)
    # 增加评论
    # comment = models.OneToManyField()
    class Meta:
        verbose_name = "文章"
        verbose_name_plural = "全部文章"

    def __str__(self):
        return self.title

# 设置轮播图
class Carousel(models.Model):
    name = models.CharField("图片名称", max_length=50)
    title = models.CharField("标题", max_length=100, null=True, blank=True)
    context = models.CharField("简介", max_length=200, null=True, blank=True)
    img = models.ImageField("展示的图片", upload_to="carousel/%Y/%m/", height_field=None, width_field=None, max_length=None, null=True, blank=True)
    showFlag = models.BooleanField("设置是否显示", default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "轮播图"
        verbose_name_plural = "全部轮播图"

templates/header.html
{% block header %}
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!-- 设置标志和折叠特效，更加适合自适应界面 -->
        <div class="navbar-header">
            <!-- 设置折叠页面的按钮 -->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                data-target="#navbar-collapse-head">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{% url 'article:home'%}" class="navbar-brand" style="font-size:2em;">LT</a>
        </div>

        <!-- 折叠的内容 -->
        <div class="collapse navbar-collapse" id="navbar-collapse-head">
            <ul class="nav navbar-nav nav-pills m-header-font">

                {% for first in first_category %}
                <li class="nav-item  header-item"><a href="{% url 'article:category' first.urlname %}"
                        class="nav-link">{{first.name}}</a>
                    <ul class="header-ul">
                        {%for second in second_category %}
                        {% if second.father == first %}
                        <li><a href="{% url 'article:category' second.urlname %}">{{ second.name}}</a></li>
                        {% endif %}
                        {% endfor %}
                    </ul>
                </li>
                {% endfor %}
                <!-- 手动设置目录 -->


                <!-- <li class="nav-item active" ><a href="#" class="nav-link">电影</a></li>
                    <li class="nav-item"><a href="#" class="nav-link">读书</a></li>
                    <li class="nav-item"><a href="#" class="nav-link">摄影</a></li>
                    <li class="nav-item"><a href="#" class="nav-link">旅游</a></li> -->
            </ul>

            <!-- 导航栏的的搜索框 -->
            <div class="search navbar-right ">
                <form class="navbar-form navbar-left" action="{% url 'article:search'%}">
                    <!-- {% csrf_token %} -->
                    <div class="form-group input-group">
                        <input type="text" class="form-control" placeholder="Search" id="search" name="search">
                        <span class="input-group-btn">
                            <button type="submit" class="btn btn-default">
                                    搜索
                            </button>
                        </span>
                    </div>
                    
                </form>


                {% if user.is_authenticated %}

                <!-- 实现用户按钮 -->
                <!-- <div class="btn-group m-header-button">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        {{ user.username }} <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" style="min-width: 100%; text-align: center;">
                        <li><a href="{% url 'article:home' %}admin/">管理</a></li>
                        <li><a href="{% url 'users:logout' %}">退出</a></li>
                    </ul>
                </div> -->
                <div class="m-header-button navbar-right m-moblie-width" >
                    <button id="m-admin-button" class="btn btn-primary m-header-button m-moblie-width">{{user.username}}</button>
                    <ul class="m-admin-ul m-moblie-width hidden">
                        <li class="m-admin-li"><a href="{% url 'article:home' %}admin/">管理</a></li>
                        <li class="m-admin-li"><a href="{% url 'users:logout' %}">退出</a></li>
                    </ul>
                </div>

                
                <!-- <button type="button" class="btn btn-default ">
                        {{ user.username }}
                    </button>
                    <button type="button" class="btn btn-primary "><a
                            href="{% url 'article:home' %}admin/">管理</a></button>
                    <button type="button" class="btn btn-danger "><a href="{% url 'users:logout' %}">退出</a></button> -->


                {% else %}
                <div class="btn-group m-header-button">
                    <a href="{% url 'users:login' %}?next_page={{ request.path }}"><button type="button"
                            class="btn btn-default">登录</button> </a>
                </div>
                {% endif%}



            </div>

        </div>
    </div>
</nav>


<!-- JavaScript -->
<script>
    $("#m-admin-button").click(function(){
        $(".m-admin-ul.m-moblie-width").toggleClass("hidden");
    });

</script>


{% endblock header %}

templates/index.html
<!-- 只能在Python Django进行继承页面 -->
{% extends "base.html" %}
{% load staticfiles %}


<!-- 拓展标题 -->
{% block title %} 刘龙韬的博客-首页 {% endblock title %}
<!-- 拓展标题结束 -->

{% block body%}
<!-- 左侧：文章详情页 -->
<div class="col-md-9 ">
    <div class="row">
        <!-- 轮播图 -->
        <div class="col-md-12">
            {% if carousal %}
            <div id="myCarousel" class="carousel slide" style="height: 300px;" data-ride="carousel"
                data-interval="2000">
                <!-- 轮播页面的指标 -->
                <div class="carousel-indicators">
                    {% for car in carousal %}
                    {% if forloop.counter0 == 0 %}
                    <li data-target="#myCarousel" data-slide-to="{{ forloop.counter0 }}" class="active"></li>
                    {% else %}
                    <li data-target="#myCarousel" data-slide-to="{{ forloop.counter0 }}"></li>
                    {% endif %}
                    {% endfor %}
                </div>


                <!-- 轮播的项目 -->
                <div class="carousel-inner">
                    {% for car in carousal %}
                    {% if forloop.counter0 == 0 %}
                    <div class="item active">
                        <img src="/media/{{ car.img }}" alt="{{ car.name }}" style="width:100%;height:300px">
                        <div class="carousel-caption">
                            {%if car.title %} <h3>{{ car.title }}</h3>{% endif %}
                            {%if car.context %}<p>{{ car.context }}</p> {% endif %}
                        </div>
                    </div>
                    {% else %}
                    <div class="item">
                        <img src="/media/{{ car.img }}" alt="{{ car.name }}" style="width:100%;height:300px">
                        <div class="carousel-caption">

                            {%if car.title %} <h3>{{ car.title }}</h3>{% endif %}
                            {%if car.context %}<p>{{ car.context }}</p> {% endif %}


                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>

                <!-- 轮播导航 -->
                <a href="#myCarousel" class="carousel-control left" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                    <span class="sr-only">Previous</span>
                </a>

                <a href="#myCarousel" class="carousel-control right" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                    <span class="sr-only">Next</span>
                </a>
                <!-- 轮播图结束 -->
            </div>

            {% else %}
            <div id="myCarousel" class="carousel slide" style="height: 300px;" data-ride="carousel"
                data-interval="2000">
                <!-- 轮播页面的指标 -->
                <div class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </div>

                <!-- 轮播的项目 -->
                <div class="carousel-inner">
                    <div class="item active">
                        <img src="{% static 'img/gir_1.jpg'%}" alt="First Gril" style="width:100%;height:300px">
                        <div class="carousel-caption">
                            <h3>人生就像一场旅行</h3>
                            <p>想要看到绝美的风景，就要走到无人踏足的地方！</p>
                        </div>
                    </div>
                    <div class="item">
                        <img src="{% static 'img/gir_2.jpg'%}" alt="Second Gril" style="width:100%;height:300px">
                    </div>
                    <div class="item">
                        <img src="{% static 'img/gir_3.jpg'%}" alt="Third Gril" style="width:100%;height:300px">
                    </div>
                </div>

                <!-- 轮播导航 -->
                <a href="#myCarousel" class="carousel-control left" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                    <span class="sr-only">Previous</span>
                </a>

                <a href="#myCarousel" class="carousel-control right" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                    <span class="sr-only">Next</span>
                </a>
                <!-- 轮播图结束 -->
            </div>

            {% endif %}
        </div>

        <div class="col-md-12" id="index_article">
            <div class="article">

                {%  for article in articles %}
                <div class="m-item row" style="margin-left: 0;"> 
                    <!-- 设置左侧样式 -->
                    <div class="col-md-8  col-sm-12 col-xs-12 m-index-content">
                        <div class="m-title ">
                            <a href="{% url 'article:detail' article.id %}">
                                {{ article.title }}
                            </a>
                        </div>

                        <div class="m-content">

                            <a href="{% url 'article:detail' article.id %}">
                        
                                {{ article.context|truncatechars_html:100|safe }}
                               
                            </a>
                        </div>

                        <div class="m-info ">
                            <ul class="m-ul-inline">
                                <li><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;<a
                                        href="#">{{ article.author }}</a></li>
                                </li>
                                <li> <span class="glyphicon glyphicon-time"
                                        aria-hidden="true"></span>&nbsp;{{  article.created_time|date:"Y/m/d"}}</li>
                                <li><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>&nbsp;<a
                                        href="{% url 'article:category' article.category.urlname %}">&nbsp;{{ article.category.name}}</a>
                                </li>
                                <li><span class="glyphicon glyphicon-eye-open"
                                        aria-hidden="true"></span>&nbsp;&nbsp;{{ article.views}}</li>
                                <li><span class="glyphicon glyphicon-edit"
                                        aria-hidden="true"></span>评论：{{ article.comment.count}}</li>

                            </ul>
                        </div>

                    </div>

                    <!-- 设置图片 -->
                    <div class="col-md-4  col-sm-12 col-xs-12 m-index-img">
                            {% if article.img %}
                            <div class=" m-fill m-img">
                                <img class="  m-radius  m-fill m-img" src="media/{{ article.img }}" alt="">
                            </div>

                            {% else %}
                            <div class=" m-fill m-img">
                                <img class="  m-radius  m-fill m-img" src="https://picsum.photos/200/300?random={{article.id}}" alt="">
                            </div>

                            {% endif %}
                    </div>

                </div>
                {% endfor %}


                <!-- <div class="article-item">
                                    <div class="article-header">
                                        这是我的一篇文章
                                    </div>
                                    <div class="article-views">
                                        <p>文章的内容是。。。</p> 
                                    </div>
                                    <div class="article-info">
                                        <ul>
                                            <li><a href="#"> 作者：</a> </li>                                            </li>
                                            <li><a href="#">发表日期：</a> </li>
                                            <li><a href="#">分类</a></li>
                                        </ul>  
                                    </div>                                
                            </div>

                            <div class="article-item">
                                    <div class="article-header">
                                        这是我的一篇文章
                                    </div>
                                    <div class="article-views">
                                        <p>文章的内容是。。。</p> 
                                    </div>
                                    <div class="article-info">
                                        <ul>
                                            <li><a href="#">作者：</a>  </li>                                            </li>
                                            <li><a href="#">发表日期：</a> </li>
                                            <li><a href="#">分类</a></li>
                                        </ul>  
                                    </div>                                
                            </div> -->
            </div>

        </div>

        <!-- 设置文章的页码 -->
        <div class="col-md-12">
            <div class="panginator">
                <nav aria-label="Page navigation">
                    <ul class="pagination pagination-lg">
                        {% if articles.has_previous %}
                        <li>
                            <a href="?page={{ articles.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        {% else %}
                        <li>
                            <a href="?page={{ articles.number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        {% endif %}

                        {% for page in pages.page_range %}
                        <li {% if page == articles.number %} class="active" {% endif %}><a
                                href="?page={{ page }}">{{ page }}</a></li>
                        {% endfor%}

                        {% if articles.has_next %}
                        <li>
                            <a href="?page={{ articles.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                        {% else %}
                        <li>
                            <a href="?page={{ articles.number}}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
            </div>

        </div>


    </div>

</div>

{% endblock %}

templates/list.html
{% extends "base.html" %}
{% load staticfiles %}

<!-- 拓展标题 -->
{% block title %} 刘龙韬的博客-列表{{ list_name }} {% endblock title %}
<!-- 拓展标题结束 -->

{% block body %}
<div class="col-md-9 ">
    <div class="row">
        <!-- 列表内容 -->
        <div class=" col-md-12 ">
            <div class="list-detail-group">
                <h4>列表：{{ list_name }}({{ lists.count }})</h4>
            </div>
        </div>
        <!-- 文章列表 -->
        <div class="col-md-12" id="index_article">
            <div class="article">

                {% for article in lists %}
                <div class="m-item row" style="margin-left: 0;">
                    <!-- 设置左侧样式 -->
                    <div class="col-md-8  col-sm-12 col-xs-12 m-index-content">
                        <div class="m-title ">
                            <a href="{% url 'article:detail' article.id %}">
                                {{ article.title }}
                            </a>
                        </div>

                        <div class="m-content">

                            <a href="{% url 'article:detail' article.id %}">

                                {{ article.context|truncatechars_html:100|safe }}

                            </a>
                        </div>

                        <div class="m-info ">
                            <ul class="m-ul-inline">
                                <li><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;<a
                                        href="#">{{ article.author }}</a></li>
                                </li>
                                <li> <span class="glyphicon glyphicon-time"
                                        aria-hidden="true"></span>&nbsp;{{  article.created_time|date:"Y/m/d"}}</li>
                                <li><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>&nbsp;<a
                                        href="{% url 'article:category' article.category.urlname %}">&nbsp;{{ article.category.name}}</a>
                                </li>
                                <li><span class="glyphicon glyphicon-eye-open"
                                        aria-hidden="true"></span>&nbsp;&nbsp;{{ article.views}}</li>
                                <li><span class="glyphicon glyphicon-edit"
                                        aria-hidden="true"></span>评论：{{ article.comment.count}}</li>

                            </ul>

                        </div>

                    </div>

                    <!-- 设置图片 -->
                    <div class="col-md-4  col-sm-12 col-xs-12 m-index-img">
                            {% if article.img %}
                            <div class=" m-fill m-img">
                                <img class="  m-radius  m-fill m-img" src="media/{{ article.img }}" alt="">
                            </div>

                            {% else %}
                            <div class=" m-fill m-img">
                                <img class="  m-radius  m-fill m-img" src="https://picsum.photos/200/300?random={{article.id}}" alt="">
                            </div>

                            {% endif %}
                    </div>

                </div>
                {% endfor %}

            </div>

        </div>

        <!-- 设置文章的页码 -->
        <div class="col-md-12">
            <div class="panginator">
                <nav aria-label="Page navigation">
                    <ul class="pagination pagination-lg">
                        {% if lists.has_previous %}
                        <li>
                            <a href="?page={{ lists.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        {% else %}
                        <li>
                            <a href="?page={{ lists.number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        {% endif %}

                        {% for page in pages.page_range %}
                        <li {% if page == lists.number %} class="active" {% endif %}><a
                                href="?page={{ page }}">{{ page }}</a></li>
                        {% endfor%}

                        {% if lists.has_next %}
                        <li>
                            <a href="?page={{ lists.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                        {% else %}
                        <li>
                            <a href="?page={{ lists.number}}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>

        </div>

    </div>

</div>
     <script>
                        $(document).ready(function () {
                            var urls = window.location.href;
                            if (urls.indexOf('?') != -1) {
                                var params = urls.split('?');

                                if (params[1].indexOf('&') != 1) {
                                    var param_list = params[1].split('&');
                                }
                                else {
                                    var param_list = params[1];
                                }
                                var url = '';
                                for (var i = 0; i < param_list.length; i++) {
                                    if (param_list[i].indexOf('page') == 0) {
                                        continue;
                                    } else {
                                        url += '&' + param_list[i];
                                    }
                                }

                                // console.log(param_list);
                                // console.log('url=', url);

                                var pages = document.querySelectorAll(".pagination.pagination-lg a");
                                // var pages = page.getElementsByTagName("a");
                                // var page_a = page.getElementsByTagsName("a");
                                for (var i = 0; i < pages.length; i++) {
                                    pages[i].href += url;
                                    // console.log(pages[i].href)
                                }
                            }
                        });


                        //对数据进行测试
                        $(document).ready(function(){
                            // console.log({{ lists }});
                        //    var lists = {{ lists }};
                        $.ajax({
                            url: "/api/category/Django",
                            type: "GET",
                            contentType: "application/json",
                            dataType: "json",
                            success: function(result){
                                console.log(result);
                                // let data = result[0];
                                // console.log(data);
                                // console.log(data.fields.title);
                                // console.log(decodeURIComponent(data.fields.title));

                            }
                        })
                        });
                    </script>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %} 登录 {% endblock %}

{% block body %}

<div class="row">
    <div class="form-style">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ forms.username.id_for_tag }}">用户名</label>
                {{ forms.username }}
                {{ forms.username.error }}

            </div>
            <div class="form-group">
                <label for="{{ forms.username.id_for_tag }}">密码</label>
                {{ forms.password }}
                {{ forms.password.error }}
            </div>
            <input type="hidden" name="next_page" value={{next_page}}>
            <button type="submit" class="btn btn-primary">登录</button>
            <a href="{% url 'users:register' %}"><button type="button" class="btn btn-primary">注册</button></a>

        </form>
    </div>



</div>

{% endblock %}

{% block right-menu %}
{% endblock %}

templates/right.html
    <div class="panel panel-default">
        <div class="panel-heading">
            最新文章
        </div>
        <div class="panel-body ">
            <ol class="side-bar-ol">
                {% for article in hot_articles %}
                <li><a href="{% url 'article:detail' article.id %}">{{ article.title }}</a></li>
                {% endfor %}
    
                <!-- <li><a href="#">我的第二个文章</a></li>
                        <li><a href="#">我的第三个文章</a></li> -->
            </ol>
        </div>
    </div>
    
    <div class="panel panel-default">
        <div class="panel-heading">
            分类
        </div>
        <div class="panel-body">
            <ul class="side-bar-ul">
    
                {% for category in categorys %}
                <li><a href="{% url 'article:category' category.urlname %}">{{ category.name }} ({{ category.article_set.count }})</a></li>
                {% endfor %}
    
                <!-- <li><a href="#">Django</a></li>
                            <li><a href="#">html</a></li>
                            <li><a href="#">java</a></li> -->
            </ul>
        </div>
    </div>
    
    <div class="panel panel-default">
        <div class="panel-heading">
            标签
        </div>
        <div class="panel-body ">
            <ul class="side-bar-ul">
                {% for tag in tags %}
                <li><a href="{% url 'article:tags' tag.name %}">{{ tag.name}} ({{ tag.article_set.count}})</a></li>
                {% endfor %}
    
                <!-- <li><a href="#">Django</a></li>
                            <li><a href="#">html</a></li>
                            <li><a href="#">java</a></li> -->
            </ul>
        </div>
    </div>