myblog/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

# 设置APP名称
app_name = 'blog'

urlpatterns = [
    # path('', include('blog.urls')),
    path('test/', views.test, name="test" ),
    path('article/<int:aid>', views.detail, name="detail"),
    # 分类列表
    path('category/<url_name>', views.category_list, name="category"),
    path('tags/<tag>', views.tag, name="tags"),
    path('search/', views.Search, name="search"),
    path('', views.index, name="home"),
]

myblog/comment/urls.py
from django.urls import path
from . import views


app_name = 'comment'

urlpatterns = [
    # 一级回复
    path('post-comment/<int:article_id>', views.post_comment, name="post_comment"),
    # 二级回复
    path('post-comment/<int:article_id>/<int:parent_comment_id>',views.post_comment, name="comment_reply"),
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from userprofile import urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('comment/', include('comment.urls', namespace='comment')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('mdeditor/', include('mdeditor.urls')),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('register/', views.user_register, name="register"),
    path('delete/<int:id>/', views.user_delete, name='delete'),
]

myblog/templates/detail.html
{% extends "base.html" %}
{% load staticfiles %}

<!-- 拓展文章详情页 -->
{% block body%}
<div class="col-md-9 ">
    <div class="row">
        <!-- 文章详细页面 -->
        <div class="col-md-12 article-detail-group">
            <!-- 文章的标题 -->
            <div class="article-detail-header">
                <h3>{{ article.title }}</h3>

                <!-- 文章的作者、分类等 -->
                <div class="article-detail-auth">
                    <ul>
                        <li>日期: {{ article.created_time|date:"Y/m/d"}}</li>
                        <li>作者: <a href="#"> {{ article.author }}</a></li>
                        <li>分类: <a
                                href="{% url 'blog:category' article.category.url_name %}">{{  article.category }}</a>
                        </li>
                        <li>阅读: {{ article.views}}</li>
                    </ul>
                </div>
            </div>

            <!-- 文章内容 -->
            <div class="article-detail-content">
                <!-- 在article的后面加入safe过滤器 -->
                {{ article.body|safe }}
            </div>

            <!-- 版权说明 -->
            <div class="article-detail-copyright">
                <ul>
                    <li><strong>网站名称: </strong><a href="http://www.liulongtao.com/">刘龙韬的博客</a></li>
                    <li><strong>本文链接: </strong><a
                            href="{% url 'blog:detail' article.id %}">www.liulongtao.com/article/{{ article.id }}</a>
                    </li>
                    <li><strong>版权声明: </strong>未经允许，禁止转载！</li>
                </ul>
            </div>

            <!-- 其他文章 -->
            <div class="article-detail-other">
                <h3>相关文章：</h3>
                <ol>
                    <li><a href="#">第一篇文章</a></li>
                    <li><a href="#">第二篇文章</a></li>
                    <li><a href="#">第三篇文章</a></li>
                    <li><a href="#">第四篇文章</a></li>

               </ol>
            </div>
        </div>

        <!-- 文章评论 -->
        <div class="col-md-12 article-detail-comment">
            <!-- 提交评论 -->
            <h3>提交评论</h3>
            <div class="commet-put">
                <!-- <p>请先登录后进行评论</p> -->

                {% if user.is_authenticated %}
                <form action="{% url 'comment:post_comment' article.id %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="body">
                            <strong>我也要发言</strong>
                        </label>

                        <textarea class="form-control" name="body" id="body" cols="30" rows="2"></textarea>
                        <!-- 提交按钮 -->
                        <button type="submit" class="btn btn-primary">发送</button>
                    </div>

                </form>

                {% else %}

                <p>请先 <a href="{% url 'userprofile:login'%}">登录</a> 后进行评论</p>
                {% endif %}

            </div>
            <!-- 全部评论 -->
            <h3>评论列表</h3>
            <div class="comment-list">
                <!-- <p>该文章没有评论，赶紧进行评论吧！</p> -->
                <!-- <h4>共有{{ comments.count }}评论</h4>
                <div>
                    {% for comment in comments %}
                    <hr>
                    <p>
                        <strong style="color: pink">
                            {{ comment.user }}
                        </strong> 于
                        <span style="color: green">
                            {{ comment.created|date:"Y-m-d H:i:s" }}
                        </span> 时说：
                    </p>
                    <pre style="font-family: inherit; font-size: 1em;">
                            {{ comment.body }}</pre>
                    {% endfor%}
                </div> -->

                {% load mptt_tags %}
                <h4>共有{{ comments.count }}条评论</h4>
                <div class="row">
                    <!-- 遍历树形结构 -->
                    {% recursetree comments %}
                    <!-- 给 node 取个别名 comment -->
                    {% with comment=node %}
                    <div class="{% if comment.reply_to %}
                        col-md-offset-1 col-11
                        {% else %}
                        col-12
                        {% endif %}">
                        <hr>
                        <p>
                            <strong style="color: pink">
                                {{ comment.user }}
                            </strong>

                            {% if comment.reply_to %}
                            <i class="far fa-arrow-alt-circle-right" style="color: cornflowerblue;"></i>
                            <strong style="color: pink">
                                {{ comment.reply_to }}
                            </strong>
                            {% endif %}

                        </p>
                        <div>{{ comment.body|safe }}</div>

                        <div>
                            <span style="color: gray">
                                {{ comment.created|date:"Y-m-d H:i" }}
                            </span>

                            <!-- 加载 modal 的按钮 -->
                            {% if user.is_authenticated %}
                            <button type="button" class="btn btn-light btn-sm text-muted"
                                onclick="load_modal({{ article.id }}, {{ comment.id }})">
                                回复
                            </button>
                            {% else %}
                            <a class="btn btn-light btn-sm text-muted" href="{% url 'userprofile:login' %}">
                                回复
                            </a>
                            {% endif %}
                        </div>

                        <!-- Modal -->
                        <div class="modal fade" id="comment_{{ comment.id }}" tabindex="-1" role="dialog"
                            aria-labelledby="CommentModalCenter" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                                <div class="modal-content" style="height: 480px">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalCenterTitle">回复 {{ comment.user }}：</h5>
                                    </div>
                                    <div class="modal-body" id="modal_body_{{ comment.id }}"></div>
                                </div>

                            </div>
                        </div>

                        {% if not comment.is_leaf_node %}
                        <div class="children">
                            {{ children }}
                        </div>
                        {% endif %}
                    </div>


                    {% endwith %}
                    {% endrecursetree %}
                </div>


                {% block script %}


                <!-- 新增代码，唤醒二级回复的 modal -->
                <script>
                    // 加载 modal
                    function load_modal(article_id, comment_id) {
                        let modal_body = '#modal_body_' + comment_id;
                        let modal_id = '#comment_' + comment_id;

                        // 加载编辑器
                        if ($(modal_body).children().length === 0) {
                            let content = '<iframe src="/comment/post-comment/' +
                                article_id +
                                '/' +
                                comment_id +
                                '"' +
                                ' frameborder="0" style="width: 100%; height: 100%;" id="iframe_' +
                                comment_id +
                                '"></iframe>';
                            $(modal_body).append(content);
                            $(modal_body).css('height', '90%');
                        };

                        $(modal_id).modal('show');
                    }
                </script>
                {% endblock script %}

            </div>
        </div>
    </div>
</div>
{% endblock %}

myblog/templates/header.html
{% block header %}
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!-- 设置标志和折叠特效，更加适合自适应界面 -->
        <div class="navbar-header">
            <!-- 设置折叠页面的按钮 -->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                data-target="#navbar-collapse-head">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{% url 'blog:home'%}" class="navbar-brand" style="font-size:2em;">LT</a>
        </div>

        <!-- 折叠的内容 -->
        <div class="collapse navbar-collapse" id="navbar-collapse-head">
            <ul class="nav navbar-nav nav-pills" style="font-size:16px;">

                <!-- {% for cate in categorys %}
                <li class="nav-item "><a href="{% url 'blog:category' cate.name %}" class="nav-link">{{ cate.name }}</a> </li>
                {% endfor %} -->

                <!-- 手动设置目录 -->
                <li class="nav-item "><a href="{% url 'blog:category' 'code' %}" class="nav-link"><span class="glyphicon glyphicon-th-large span-icon" aria-hidden="true"></span>编程</a> </li>
                <li class="nav-item "><a href="{% url 'blog:category' 'read' %}" class="nav-link"><span class="glyphicon glyphicon-book span-icon" aria-hidden="true"></span>读书</a> </li>
                <li class="nav-item "><a href="{% url 'blog:category' 'movie'%}" class="nav-link"><span class="glyphicon glyphicon-film span-icon" aria-hidden="true"></span>电影</a> </li>
                <li class="nav-item "><a href="{% url 'blog:category' 'life' %}" class="nav-link"><span class="glyphicon glyphicon-user span-icon" aria-hidden="true"></span>日常闲聊</a> </li>


                <!-- <li class="nav-item active" ><a href="#" class="nav-link">电影</a></li>
                    <li class="nav-item"><a href="#" class="nav-link">读书</a></li>
                    <li class="nav-item"><a href="#" class="nav-link">摄影</a></li>
                    <li class="nav-item"><a href="#" class="nav-link">旅游</a></li> -->
            </ul>

            <!-- 导航栏的的搜索框 -->
            <div class="search navbar-right">
                <form class="navbar-form navbar-left" method="get" action="{% url 'blog:search' %}" >
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search" id="search" name="search">
                    </div>
                    <button type="submit" class="btn btn-default">
                        提交
                    </button>
                </form>

                {% if user.is_authenticated %}
                <!-- 如果用户已经登录，则显示用户名和下拉菜单 -->
                <span class="nav navbar-nav ">
                    <ul class="nav navbar-nav text-center" style="font-size:16px;">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="{% url 'blog:home'%}admin" id="navbarDropdown"
                                role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ user.username }}
                            </a>
                            <!-- <div class="dropdown-menu" aria-labelledby="navbarDropdown"> -->
                            <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
                                <li><a class="dropdown-item" href="{% url 'blog:home'%}admin" class="nav-link">用户管理</a></li>
                                <li><a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a></li>
                                <li><a class="dropdown-item" href="{% url 'userprofile:logout'%}">退出登录</a></li>
                            </ul>

                        </li>
                    </ul>
                </span>

                {% else %}
                <!-- 如果用户没有登录，则显示登录按钮 -->
                <!-- 登陆/注册 -->
                <span class="nav navbar-nav ">
                    <ul class="nav navbar-nav text-center" style="font-size:16px;">
                        <!-- <li class="nav-item"><a href="{% url 'blog:home'%}admin" class="nav-link">登录|注册</a></li> -->
                        <li class="nav-item"><a href="{% url 'userprofile:login' %}" class="nav-link">登录</a></li>
                    </ul>
                </span>
                <!-- 结束判断是否登录 -->
                {% endif%}
            </div>

        </div>
    </div>
</nav>

{% if user.is_authenticated %}
<script>
    function user_delete(){
        // 调用layer弹窗组件
        layer.open({
            title: "确认删除",
            content: "确认删除用户资料吗？",
            yes: function(index, layero){
                location.href = "{% url 'userprofile:delete' user.id %}"
            }
        });
    }
</script>
{% endif %}

{% endblock header %}

myblog/templates/index.html
<!-- 只能在Python Django进行继承页面 -->
{% extends "base.html" %}
{% load staticfiles %}
{% block body%}  
            <!-- 左侧：文章详情页 -->
            <div class="col-md-9 ">
                <div class="row">
                     <!-- 轮播图 -->
                    <div class="col-md-12">
                        <div id="myCarousel" class="carousel slide" style="height: 300px;" data-ride="carousel" data-interval="2000">
                            <!-- 轮播页面的指标 -->
                            <div class="carousel-indicators">
                                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                                <li data-target="#myCarousel" data-slide-to="1"></li> 
                                <li data-target="#myCarousel" data-slide-to="2" ></li>
                            </div>

                            <!-- 轮播的项目 -->
                            <div class="carousel-inner">
                                <div class="item active">
                                    <img src="{% static 'img/gir_1.jpg'%}" alt="First Gril" style="width:100%;height:300px" >
                                    <div class="carousel-caption">
                                        <h3>beautiful girls</h3>
                                        <p>everyone like beatiful grils!</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="{% static 'img/gir_2.jpg'%}" alt="Second Gril" style="width:100%;height:300px">
                                </div>
                                <div class="item">
                                    <img src="{% static 'img/gir_3.jpg'%}" alt="Third Gril" style="width:100%;height:300px" >
                                </div>
                            </div>

                            <!-- 轮播导航 -->
                            <a href="#myCarousel" class="carousel-control left" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left"></span>
                            <span class="sr-only">Previous</span>
                            </a>

                            <a href="#myCarousel" class="carousel-control right" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                                <span class="sr-only">Next</span>
                            </a>
                            <!-- 轮播图结束 -->
                        </div>
                    </div>

                    <div class="col-md-12" id="index_article">
                        <div class="article">

                            {%  for article in articles %}
                            <div class="article-item">
                                <div class="article-header">
                                    <a href="{% url 'blog:detail' article.id %}">{{ article.title }}</a>
                                </div>
                                <div class="article-views">
                                    <p>{{ article.content|truncatewords:20 }}</p> 
                                </div>
                                <div class="article-info">
                                    <ul>
                                        <li>作者：<a href="{% url 'blog:home'%}author-{{article.author.id}}">{{ article.author }}</a></li>                                            </li>
                                        <li>发表日期：<a href="#">{{ article.created_time }} </a></li>
                                        <li>分类: <a href="{% url 'blog:category' article.category.name %}">{{ article.category.name }}</a></li>
                                    </ul>  
                                </div>                                
                            </div>
                            {% endfor %}

                            <!-- <div class="article-item">
                                    <div class="article-header">
                                        这是我的一篇文章
                                    </div>
                                    <div class="article-views">
                                        <p>文章的内容是。。。</p> 
                                    </div>
                                    <div class="article-info">
                                        <ul>
                                            <li><a href="#"> 作者：</a> </li>                                            </li>
                                            <li><a href="#">发表日期：</a> </li>
                                            <li><a href="#">分类</a></li>
                                        </ul>  
                                    </div>                                
                            </div>

                            <div class="article-item">
                                    <div class="article-header">
                                        这是我的一篇文章
                                    </div>
                                    <div class="article-views">
                                        <p>文章的内容是。。。</p> 
                                    </div>
                                    <div class="article-info">
                                        <ul>
                                            <li><a href="#">作者：</a>  </li>                                            </li>
                                            <li><a href="#">发表日期：</a> </li>
                                            <li><a href="#">分类</a></li>
                                        </ul>  
                                    </div>                                
                            </div> -->
                        </div>

                    </div>

                    <!-- 设置文章的页码 -->
                    <div class="col-md-12">
                        <div class="panginator">
                            <div class="page-info">
                                <ul class="pangination panginator-ul">
                                    <!-- 页面页码 -->
                                    {% if list_artilcle.has_previous %}
                                    <li><a href="?page=1">
                                        <span class="glyphicon glyphicon-step-backward">
                                    </span></a></li>
                                        <li><a href="?page={{ list_article.previous_page_number }}"><span class="glyphicon glyphicon-chevron-left">
                                    </span></a></li>
                                    {% endif %}

                                    <li><span> <a href="?page={{ list_article.number }}">
                                            {{ list_article.number }} of {{ list_article.paginator.num_pages }}
                                        </a>
                                    </span></li>

                                    {% if list_article.has_next %}
                                        <li><a href="?page={{ list_article.next_page_number }}"><span class="glyphicon glyphicon-chevron-right">
                                    </span></a></li>        
                                        <li><a href="?page={{ list_article.paginator.num_pages }}"><span class="glyphicon glyphicon-step-forward">    
                                    </span></a></li>
                                    {% endif %}
                                </ul>
                            </div>
                           
                        </div>
                    </div>
                    
                    
                </div>
               
            </div>

            {% endblock %}

myblog/templates/right.html
{% block right-menu %}
<div class="col-md-3  hidden-xs">

        {% block right-menu-add %}{% endblock right-menu-add %}
        <div class="panel panel-default">
            <div class="panel-heading">
                最新文章
            </div>
            <div class="panel-body ">
                <ol class="side-bar-ol">
                    {% for article in right_articles %}
                    <li><a href="{% url 'blog:detail' article.id%}">{{ article.title }}</a></li>
                    {% endfor %}
                    
                    <!-- <li><a href="#">我的第二个文章</a></li>
                    <li><a href="#">我的第三个文章</a></li> -->
                </ol>
            </div>
        </div>

        <div class="panel panel-default">
                <div class="panel-heading">
                    分类
                </div>
                <div class="panel-body">
                    <ul  class="side-bar-ul">

                        {% for category in categorys %}
                        <li><a href="{% url 'blog:category' category.url_name %}">{{ category.name }}</a></li>
                        {% endfor %}
                       
                        <!-- <li><a href="#">Django</a></li>
                        <li><a href="#">html</a></li>
                        <li><a href="#">java</a></li> -->
                    </ul>
                </div>
        </div>

        <div class="panel panel-default">
                <div class="panel-heading">
                    标签
                </div>
                <div class="panel-body ">
                    <ul  class="side-bar-ul">
                        {% for tag in tags %}
                        <li><a href="{% url 'blog:tags' tag.name %}">{{ tag.name}}</a></li>
                        {% endfor %}
                        
                        <!-- <li><a href="#">Django</a></li>
                        <li><a href="#">html</a></li>
                        <li><a href="#">java</a></li> -->
                    </ul>
                </div>
        </div>
    </div>

    {% endblock right-menu %}